name: Start PostgreSQL in Docker

on:
  push:
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/docker-postgres.yml'

jobs:
  postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "PostgreSQL is up!" && break
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

      - name: Verify DB connection
        run: |
          sudo apt update && sudo apt install -y postgresql-client
          PGPASSWORD=sep4frontend psql -h localhost -U sep4frontend -d userdb -c '\l'
